/**
 * ASCII Fallback Image Generator
 *
 * When all AI image providers are unavailable, generates a placeholder
 * image containing the prompt and style information as styled text.
 * Uses sharp to render an SVG to PNG.
 */

import sharp from 'sharp';

// ===== Constants =====

const FALLBACK_WIDTH = 1024;
const FALLBACK_HEIGHT = 768;

// ===== Helper Functions =====

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function wrapText(text: string, maxCharsPerLine: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + word).length > maxCharsPerLine) {
      lines.push(currentLine.trim());
      currentLine = word + ' ';
    } else {
      currentLine += word + ' ';
    }
  }
  if (currentLine.trim()) {
    lines.push(currentLine.trim());
  }

  return lines;
}

function generateAsciiPattern(seed: string): string {
  // Generate a simple block pattern based on the prompt hash
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash + seed.charCodeAt(i)) | 0;
  }

  const blocks = ['▓', '▒', '░', '█', '▄', '▀', '■', '□'];
  const rows = 6;
  const cols = 24;
  let pattern = '';

  for (let r = 0; r < rows; r++) {
    let row = '';
    for (let c = 0; c < cols; c++) {
      const idx = Math.abs((hash + r * cols + c) % blocks.length);
      row += blocks[idx];
    }
    pattern += `<tspan x="512" dy="20" text-anchor="middle" fill="#2a2a4a" font-size="14">${row}</tspan>`;
  }

  return pattern;
}

// ===== Main Function =====

export interface AsciiFallbackResult {
  buffer: Buffer;
  width: number;
  height: number;
}

/**
 * Generate an ASCII-style placeholder image when all AI providers fail.
 */
export async function generateAsciiFallbackImage(
  prompt: string,
  style?: string
): Promise<AsciiFallbackResult> {
  const width = FALLBACK_WIDTH;
  const height = FALLBACK_HEIGHT;

  const wrappedPrompt = wrapText(escapeXml(prompt), 90);
  const promptLines = wrappedPrompt
    .map((line, i) => {
      const y = 300 + i * 24;
      return `<tspan x="80" dy="${i === 0 ? 0 : 24}" fill="#c0c0c0" font-size="15">${line}</tspan>`;
    })
    .join('');

  const styleBlock = style
    ? `<text x="80" y="${300 + wrappedPrompt.length * 24 + 40}" font-family="monospace" font-size="16" fill="#ffffff">
       <tspan font-weight="bold">STYLE:</tspan> <tspan fill="#a0a0a0">${escapeXml(style)}</tspan>
     </text>`
    : '';

  const asciiPattern = generateAsciiPattern(prompt);

  const svg = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#0f0f23"/>
          <stop offset="100%" stop-color="#1a1a3e"/>
        </linearGradient>
      </defs>

      <!-- Background -->
      <rect width="100%" height="100%" fill="url(#bg)"/>

      <!-- Decorative border -->
      <rect x="20" y="20" width="984" height="728" rx="8" fill="none" stroke="#e94560" stroke-width="2" opacity="0.4"/>
      <rect x="24" y="24" width="976" height="720" rx="6" fill="none" stroke="#e94560" stroke-width="1" opacity="0.2"/>

      <!-- Header -->
      <text x="512" y="70" font-family="monospace" font-size="28" fill="#e94560" text-anchor="middle" font-weight="bold">
        ✦ IMAGE GENERATION UNAVAILABLE ✦
      </text>
      <text x="512" y="110" font-family="monospace" font-size="16" fill="#606080" text-anchor="middle">
        All AI image providers are currently offline. Generating ASCII placeholder instead.
      </text>

      <!-- Divider -->
      <line x1="80" y1="140" x2="944" y2="140" stroke="#e94560" stroke-width="1" opacity="0.5"/>

      <!-- ASCII Pattern -->
      <text x="512" y="170" font-family="monospace" font-size="14" text-anchor="middle">
        ${asciiPattern}
      </text>

      <!-- Prompt Section -->
      <text x="80" y="260" font-family="monospace" font-size="18" fill="#ffffff">
        <tspan font-weight="bold">PROMPT:</tspan>
      </text>
      <text x="80" y="280" font-family="monospace" font-size="15">
        ${promptLines}
      </text>

      ${styleBlock}

      <!-- Bottom divider -->
      <line x1="80" y1="${height - 80}" x2="944" y2="${height - 80}" stroke="#e94560" stroke-width="1" opacity="0.5"/>

      <!-- Footer -->
      <text x="512" y="${height - 45}" font-family="monospace" font-size="14" fill="#505070" text-anchor="middle">
        Generated by Policy Bot • ASCII Fallback Mode • All providers offline
      </text>
    </svg>
  `;

  const buffer = await sharp(Buffer.from(svg)).png().toBuffer();

  return {
    buffer,
    width,
    height,
  };
}
