/**
 * Theme Registry
 *
 * Loads, validates, and provides access to all 10 themes.
 * Each theme must define all required CSS tokens.
 *
 * Phase 1 (Token Foundation): Stub that validates theme structure.
 * Phase 2 (Theme Implementation): Full token loading and validation.
 */

import type { ThemeTokens, ThemeId } from './types';

/** All 10 theme IDs in display order */
export const THEME_IDS: ThemeId[] = [
  'portfolio',
  'product',
  'company',
  'blog',
  'documentation',
  'dashboard',
  'store',
  'event',
  'nonprofit',
  'education',
];

/** Human-readable display names for each theme */
export const THEME_DISPLAY_NAMES: Record<ThemeId, string> = {
  portfolio: 'Portfolio',
  product: 'Product',
  company: 'Company',
  blog: 'Blog',
  documentation: 'Documentation',
  dashboard: 'Dashboard',
  store: 'Store',
  event: 'Event',
  nonprofit: 'Nonprofit',
  education: 'Education',
};

/** Theme descriptions for the catalog */
export const THEME_DESCRIPTIONS: Record<ThemeId, string> = {
  portfolio: 'Personal/creative showcase for photographers, designers, and developers',
  product: 'SaaS/product marketing with landing pages and feature showcases',
  company: 'Corporate/business presence for agencies, firms, and enterprises',
  blog: 'Content publishing for blogs, magazines, and newsletters',
  documentation: 'Technical documentation for APIs, knowledge bases, and manuals',
  dashboard: 'Data/analytics interface for admin panels, monitoring, and reports',
  store: 'E-commerce for product listings, catalogs, and shops',
  event: 'Event/conference sites for meetups, workshops, and summits',
  nonprofit: 'Mission-driven organization sites for NGOs, charities, and foundations',
  education: 'Learning platform for courses, LMS, and training portals',
};

/**
 * Get the CSS path for a theme's compiled global.css.
 * CSS files are generated by Style Dictionary at build time.
 */
export function getThemeCssPath(themeId: ThemeId): string {
  return `src/lib/site-gen/themes/dist/${themeId}/global.css`;
}

/**
 * Validate that all required tokens are present in a theme.
 * Stub — full implementation in Phase 2.
 */
export function validateThemeTokens(tokens: ThemeTokens): string[] {
  const errors: string[] = [];

  const requiredColors: (keyof ThemeTokens['colors'])[] = [
    'primary', 'primary-hover', 'secondary', 'background', 'surface',
    'text', 'text-muted', 'border', 'success', 'warning', 'error',
  ];

  for (const color of requiredColors) {
    if (!tokens.colors[color]) {
      errors.push(`Missing color token: ${color}`);
    }
  }

  const requiredFonts: (keyof ThemeTokens['fonts'])[] = ['heading', 'body', 'mono'];
  for (const font of requiredFonts) {
    if (!tokens.fonts[font]) {
      errors.push(`Missing font token: ${font}`);
    }
  }

  return errors;
}

/**
 * Get all available theme IDs.
 */
export function getAllThemeIds(): ThemeId[] {
  return [...THEME_IDS];
}
