/**
 * Document layout flags per page type.
 */
import type { DocumentLayoutFlags } from '../types';

export const DOCUMENT_LAYOUT_FLAGS: Record<string, DocumentLayoutFlags> = {
  documentation: {
    showToc: true,
    tocHeading: 'Contents',
    showLangSelector: false,
    showHero: false,
    showMetadataBadge: false,
    badgeLabel: '',
    badgeStyle: 'border',
    showHeaderTitle: true,
    footerSuffix: 'Generated',
    searchPlaceholder: 'Search...',
    contentMaxWidth: '960px',
  },
  book: {
    showToc: true,
    tocHeading: 'Chapters',
    showLangSelector: true,
    showHero: false,
    showMetadataBadge: true,
    badgeLabel: 'Ebook format',
    badgeStyle: 'border',
    showHeaderTitle: true,
    footerSuffix: 'Book View',
    searchPlaceholder: 'Search book...',
    contentMaxWidth: '960px',
  },
  report: {
    showToc: true,
    tocHeading: 'Contents',
    showLangSelector: false,
    showHero: false,
    showMetadataBadge: true,
    badgeLabel: 'Formal report',
    badgeStyle: 'border-left',
    showHeaderTitle: true,
    footerSuffix: 'Report View',
    searchPlaceholder: 'Search report...',
    contentMaxWidth: '960px',
  },
  website: {
    showToc: false,
    tocHeading: 'Contents',
    showLangSelector: true,
    showHero: true,
    showMetadataBadge: false,
    badgeLabel: '',
    badgeStyle: 'border',
    showHeaderTitle: true,
    footerSuffix: 'Website Mockup',
    searchPlaceholder: 'Search website...',
    contentMaxWidth: '1200px',
  },
  webpage: {
    showToc: false,
    tocHeading: 'Contents',
    showLangSelector: false,
    showHero: false,
    showMetadataBadge: false,
    badgeLabel: '',
    badgeStyle: 'border',
    showHeaderTitle: false,
    footerSuffix: '',
    searchPlaceholder: 'Search...',
    contentMaxWidth: '960px',
  },
  dashboard: {
    showToc: false,
    tocHeading: 'Contents',
    showLangSelector: false,
    showHero: false,
    showMetadataBadge: false,
    badgeLabel: '',
    badgeStyle: 'border',
    showHeaderTitle: false,
    footerSuffix: '',
    searchPlaceholder: 'Search...',
    contentMaxWidth: '100%',
  },
  roadmap: {
    showToc: false,
    tocHeading: 'Contents',
    showLangSelector: false,
    showHero: false,
    showMetadataBadge: false,
    badgeLabel: '',
    badgeStyle: 'border',
    showHeaderTitle: true,
    footerSuffix: 'Roadmap',
    searchPlaceholder: 'Search roadmap...',
    contentMaxWidth: '960px',
  },
};
