/**
 * Client-side JavaScript bundle for generated HTML pages.
 */
export function buildJs(): string {
  const jsLines = [
    '// Mermaid init - explicit rendering with missing-library fallback',
    '(function() {',
    '  function escapeHtmlForFallback(str) {',
    '    return str',
    '      .replace(/\\x26/g, "\\x26amp;")',
    '      .replace(/\\x3C/g, "\\x26lt;")',
    '      .replace(/\\x3E/g, "\\x26gt;")',
    '      .replace(/"/g, "\\x26quot;")',
    '      .replace(/\'/g, "\\x26#39;");',
    '  }',
    '  function showDiagramTextFallback(block, code) {',
    '    block.innerHTML = "<pre style=\\"background:#fef3c7;padding:12px;border-radius:6px;overflow-x:auto;font-size:12px;\\">" +',
    '      "<strong>Diagram could not be rendered.</strong><br>Mermaid library is unavailable. Diagram source is shown below:\\n" +',
    '      escapeHtmlForFallback(code) + "</pre>";',
    '  }',
    '  if (typeof mermaid === "undefined") {',
    '    document.querySelectorAll(".mermaid[data-mermaid-source]").forEach(function(block) {',
    '      var encoded = block.getAttribute("data-mermaid-source");',
    '      if (!encoded) return;',
    '      var code = atob(encoded);',
    '      showDiagramTextFallback(block, code);',
    '    });',
    '    return;',
    '  }',
    '  mermaid.initialize({',
    '    startOnLoad: false,',
    '    theme: "default",',
    '    securityLevel: "loose",',
    '    suppressErrorRendering: true,',
    '    fontFamily: "system-ui, -apple-system, sans-serif",',
    '    flowchart: { useMaxWidth: true, htmlLabels: true, curve: "basis" },',
    '    mindmap: { useMaxWidth: true, padding: 16 }',
    '  });',
    '  var mermaidBlocks = document.querySelectorAll(".mermaid");',
    '  if (mermaidBlocks.length === 0) return;',
    '  mermaidBlocks.forEach(function(block, index) {',
    '    var encoded = block.getAttribute("data-mermaid-source");',
    '    var code = encoded ? atob(encoded) : block.textContent.trim();',
    '    if (!code) return;',
    '    var id = "mermaid-svg-" + index + "-" + Date.now();',
    '    try {',
    '      mermaid.render(id, code).then(function(result) {',
    '        block.innerHTML = result.svg;',
    '      }).catch(function(err) {',
    '        console.error("Mermaid render error:", err);',
    '        showDiagramTextFallback(block, code);',
    '      });',
    '    } catch (e) {',
    '      console.error("Mermaid render error:", e);',
    '      showDiagramTextFallback(block, code);',
    '    }',
    '  });',
    '  window.renderMermaidDiagrams = function() {',
    '    var blocks = document.querySelectorAll(".mermaid[data-mermaid-source]");',
    '    blocks.forEach(function(block, index) {',
    '      if (block.querySelector("svg")) return;',
    '      var encoded = block.getAttribute("data-mermaid-source");',
    '      if (!encoded) return;',
    '      var code = atob(encoded);',
    '      var id = "mermaid-svg-dynamic-" + index + "-" + Date.now();',
    '      try {',
    '        mermaid.render(id, code).then(function(result) {',
    '          block.innerHTML = result.svg;',
    '        }).catch(function(err) {',
    '          console.error("Mermaid render error:", err);',
    '          showDiagramTextFallback(block, code);',
    '        });',
    '      } catch (e) {',
    '        console.error("Mermaid render error:", e);',
    '        showDiagramTextFallback(block, code);',
    '      }',
    '    });',
    '  };',
    '})();',
    '',
    '// Chart.js init - explicit rendering with fallback',
    '(function() {',
    '  if (typeof Chart === "undefined") {',
    '    document.querySelectorAll("canvas[data-chart-config]").forEach(function(canvas) {',
    '      var wrapper = canvas.closest("[data-chart-wrapper]") || canvas.parentNode;',
    '      wrapper.innerHTML = "<div style=\\"padding:16px;text-align:center;color:#dc2626;background:#fef2f2;border-radius:6px;font-size:13px;\\">" +',
    '        "<strong>Chart could not be rendered.</strong><br>Chart.js library is unavailable." +',
    '        "</div>";',
    '    });',
    '    return;',
    '  }',
    '  function chartTitleFromConfig(config) {',
    '    var title = config && config.options && config.options.plugins && config.options.plugins.title;',
    '    if (!title || !title.display || !title.text) return "Chart";',
    '    return Array.isArray(title.text) ? title.text.join(" ") : String(title.text);',
    '  }',
    '  function replaceChartCanvasWithImage(canvas, chart, config) {',
    '    try {',
    '      if (!canvas || !canvas.parentNode) return;',
    '      var imageData = canvas.toDataURL("image/png");',
    '      var img = document.createElement("img");',
    '      img.src = imageData;',
    '      img.alt = chartTitleFromConfig(config);',
    '      img.setAttribute("data-chart-image", "true");',
    '      img.width = canvas.width;',
    '      img.height = canvas.height;',
    '      img.style.width = "100%";',
    '      img.style.height = "100%";',
    '      img.style.objectFit = "contain";',
    '      img.style.display = "block";',
    '      canvas.parentNode.replaceChild(img, canvas);',
    '      if (chart && typeof chart.destroy === "function") chart.destroy();',
    '    } catch (e) {',
    '      console.warn("Chart image archival failed; leaving canvas in place:", e);',
    '    }',
    '  }',
    '  function renderCharts() {',
    '    document.querySelectorAll("canvas[data-chart-config]").forEach(function(canvas) {',
    '      if (canvas.getAttribute("data-chart-rendered") === "true") return;',
    '      var encoded = canvas.getAttribute("data-chart-config");',
    '      if (!encoded) return;',
    '      try {',
    '        var config = JSON.parse(atob(encoded));',
    '        config.options = config.options || {};',
    '        config.options.animation = { duration: 0 };',
    '        config.options.responsive = true;',
    '        config.options.maintainAspectRatio = false;',
    '        var chart = new Chart(canvas.getContext("2d"), config);',
    '        canvas.setAttribute("data-chart-rendered", "true");',
    '        requestAnimationFrame(function() {',
    '          replaceChartCanvasWithImage(canvas, chart, config);',
    '        });',
    '      } catch (e) {',
    '        console.error("Chart render error:", e);',
    '        var wrapper = canvas.closest("[data-chart-wrapper]") || canvas.parentNode;',
    '        wrapper.innerHTML = "<div style=\\"padding:16px;text-align:center;color:#dc2626;background:#fef2f2;border-radius:6px;font-size:13px;\\">" +',
    '          "<strong>Chart could not be rendered.</strong><br>Invalid chart configuration." +',
    '          "</div>";',
    '      }',
    '    });',
    '  }',
    '  if (document.readyState === "loading") {',
    '    document.addEventListener("DOMContentLoaded", renderCharts);',
    '  } else {',
    '    renderCharts();',
    '  }',
    '  window.renderCharts = renderCharts;',
    '})();',
    '',
    '// TOC active link tracking',
    '(function() {',
    '  var headings = document.querySelectorAll("h2[id], h3[id], h4[id]");',
    '  var tocLinks = document.querySelectorAll(".toc-link");',
    '  if (!headings.length || !tocLinks.length) return;',
    '  var observer = new IntersectionObserver(function(entries) {',
    '    entries.forEach(function(entry) {',
    '      if (entry.isIntersecting) {',
    '        tocLinks.forEach(function(link) { link.classList.remove("active"); });',
    '        var active = document.querySelector(".toc-link[href=\\"#" + entry.target.id + "\\"]");',
    '        if (active) active.classList.add("active");',
    '      }',
    '    });',
    '  }, { rootMargin: "-20% 0px -70% 0px" });',
    '  headings.forEach(function(h) { observer.observe(h); });',
    '})();',
    '',
    '// Search functionality',
    'function searchDocs(query) {',
    '  var highlights = document.querySelectorAll(".search-highlight");',
    '  highlights.forEach(function(el) {',
    '    var parent = el.parentNode;',
    '    parent.replaceChild(document.createTextNode(el.textContent), el);',
    '    parent.normalize();',
    '  });',
    '  if (!query || query.length < 2) return;',
    '  var walker = document.createTreeWalker(',
    '    document.querySelector(".main-content") || document.body,',
    '    NodeFilter.SHOW_TEXT, null',
    '  );',
    '  var textNodes = [];',
    '  var node;',
    '  while ((node = walker.nextNode())) {',
    '    if (node.nodeValue && node.nodeValue.toLowerCase().includes(query.toLowerCase())) {',
    '      textNodes.push(node);',
    '    }',
    '  }',
    '  textNodes.forEach(function(textNode) {',
    '    var escaped = query.replace(new RegExp("[.*+?^${}()|[\\]\\\\\\\\]", "g"), "\\\\$&");',
    '    var regex = new RegExp("(" + escaped + ")", "gi");',
    '    var span = document.createElement("span");',
    '    span.innerHTML = textNode.nodeValue.replace(regex, "<mark class=\\"search-highlight\\">$1</mark>");',
    '    textNode.parentNode.replaceChild(span, textNode);',
    '  });',
    '  var first = document.querySelector(".search-highlight");',
    '  if (first) first.scrollIntoView({ behavior: "smooth", block: "center" });',
    '}',
  ];

  return jsLines.join('\n');
}
