/**
 * Client-side JavaScript bundle for generated HTML pages.
 */
import { mermaidInitConfigJson } from '@/lib/diagram-gen/mermaid-config';

export function buildJs(): string {
  const jsLines = [
    '// Mermaid init - explicit rendering with missing-library fallback',
    '(function() {',
    '  function escapeHtmlForFallback(str) {',
    '    return str',
    '      .replace(/\\x26/g, "\\x26amp;")',
    '      .replace(/\\x3C/g, "\\x26lt;")',
    '      .replace(/\\x3E/g, "\\x26gt;")',
    '      .replace(/"/g, "\\x26quot;")',
    '      .replace(/\'/g, "\\x26#39;");',
    '  }',
    '  function showDiagramTextFallback(block, code) {',
    '    block.innerHTML = "<pre style=\\"background:#fef3c7;padding:12px;border-radius:6px;overflow-x:auto;font-size:12px;\\">" +',
    '      "<strong>Diagram could not be rendered.</strong><br>Mermaid library is unavailable. Diagram source is shown below:\\n" +',
    '      escapeHtmlForFallback(code) + "</pre>";',
    '  }',
    '  if (typeof mermaid === "undefined") {',
    '    document.querySelectorAll(".mermaid[data-mermaid-source]").forEach(function(block) {',
    '      var encoded = block.getAttribute("data-mermaid-source");',
    '      if (!encoded) return;',
    '      var code = atob(encoded);',
    '      showDiagramTextFallback(block, code);',
    '    });',
    '    return;',
    '  }',
    '  mermaid.initialize(' + mermaidInitConfigJson() + ');',
    '  var mermaidBlocks = document.querySelectorAll(".mermaid");',
    '  if (mermaidBlocks.length === 0) return;',
    '  mermaidBlocks.forEach(function(block, index) {',
    '    var encoded = block.getAttribute("data-mermaid-source");',
    '    var code = encoded ? atob(encoded) : block.textContent.trim();',
    '    if (!code) return;',
    '    var id = "mermaid-svg-" + index + "-" + Date.now();',
    '    try {',
    '      mermaid.render(id, code).then(function(result) {',
    '        block.innerHTML = result.svg;',
    '      }).catch(function(err) {',
    '        console.error("Mermaid render error:", err);',
    '        showDiagramTextFallback(block, code);',
    '      });',
    '    } catch (e) {',
    '      console.error("Mermaid render error:", e);',
    '      showDiagramTextFallback(block, code);',
    '    }',
    '  });',
    '  window.renderMermaidDiagrams = function() {',
    '    var blocks = document.querySelectorAll(".mermaid[data-mermaid-source]");',
    '    blocks.forEach(function(block, index) {',
    '      if (block.querySelector("svg")) return;',
    '      var encoded = block.getAttribute("data-mermaid-source");',
    '      if (!encoded) return;',
    '      var code = atob(encoded);',
    '      var id = "mermaid-svg-dynamic-" + index + "-" + Date.now();',
    '      try {',
    '        mermaid.render(id, code).then(function(result) {',
    '          block.innerHTML = result.svg;',
    '        }).catch(function(err) {',
    '          console.error("Mermaid render error:", err);',
    '          showDiagramTextFallback(block, code);',
    '        });',
    '      } catch (e) {',
    '        console.error("Mermaid render error:", e);',
    '        showDiagramTextFallback(block, code);',
    '      }',
    '    });',
    '  };',
    '})();',
    '',
    '// Chart.js init - dashboard: interactive canvas; other pages: static image archival',
    '(function() {',
    '  // Register datalabels plugin if available (inlined from node_modules via buildVendorScripts).',
    '  // try/catch: Chart.register throws if called twice; UMD global is ChartDataLabels.',
    '  try {',
    '    if (typeof ChartDataLabels !== "undefined") Chart.register(ChartDataLabels);',
    '  } catch(e) { /* already registered or unavailable */ }',
    '',
    '  if (typeof Chart === "undefined") {',
    '    document.querySelectorAll("canvas[data-chart-config]").forEach(function(canvas) {',
    '      var wrapper = canvas.closest("[data-chart-wrapper]") || canvas.parentNode;',
    '      wrapper.innerHTML = "<div style=\\"padding:16px;text-align:center;color:#dc2626;background:#fef2f2;border-radius:6px;font-size:13px;\\">" +',
    '        "<strong>Chart could not be rendered.</strong><br>Chart.js library is unavailable." +',
    '        "</div>";',
    '    });',
    '    return;',
    '  }',
    '',
    '  var isDashboard = document.body.getAttribute("data-page-type") === "dashboard";',
    '',
    '  if (isDashboard) {',
    '    window.__dashCharts    = {};',
    '    window.__dashData      = {};',
    '    window.__dashSelection = null;',
    '  }',
    '',
    '  function chartTitleFromConfig(config) {',
    '    var title = config && config.options && config.options.plugins && config.options.plugins.title;',
    '    if (!title || !title.display || !title.text) return "Chart";',
    '    return Array.isArray(title.text) ? title.text.join(" ") : String(title.text);',
    '  }',
    '',
    '  // Used only for non-dashboard pages to convert canvas → static PNG image',
    '  function replaceChartCanvasWithImage(canvas, chart, config) {',
    '    try {',
    '      if (!canvas || !canvas.parentNode) return;',
    '      var imageData = canvas.toDataURL("image/png");',
    '      var img = document.createElement("img");',
    '      img.src = imageData;',
    '      img.alt = chartTitleFromConfig(config);',
    '      img.setAttribute("data-chart-image", "true");',
    '      img.width = canvas.width;',
    '      img.height = canvas.height;',
    '      img.style.width = "100%";',
    '      img.style.height = "100%";',
    '      img.style.objectFit = "contain";',
    '      img.style.display = "block";',
    '      canvas.parentNode.replaceChild(img, canvas);',
    '      if (chart && typeof chart.destroy === "function") chart.destroy();',
    '    } catch (e) {',
    '      console.warn("Chart image archival failed; leaving canvas in place:", e);',
    '    }',
    '  }',
    '',
    '  // Build datalabels plugin config (functions injected at runtime, not serialized)',
    '  function buildDatalabelsConfig(chartType) {',
    '    var isPie = chartType === "pie" || chartType === "doughnut";',
    '    if (isPie) {',
    '      return {',
    '        color: "#fff",',
    '        font: { weight: "bold", size: 11 },',
    '        textAlign: "center",',
    '        formatter: function(value, ctx) {',
    '          var total = ctx.chart.data.datasets[0].data.reduce(function(a, b) { return a + b; }, 0);',
    '          var pct = total > 0 ? ((value / total) * 100).toFixed(1) : "0";',
    '          return value + "\\n(" + pct + "%)";',
    '        },',
    '        display: function(ctx) {',
    '          var arc = ctx.chart.getDatasetMeta(ctx.datasetIndex).data[ctx.dataIndex];',
    '          return arc ? (arc.outerRadius - (arc.innerRadius || 0)) / 2 > 20 : false;',
    '        },',
    '      };',
    '    }',
    '    return {',
    '      anchor: "end",',
    '      align: "top",',
    '      font: { size: 10, weight: "600" },',
    '      color: "#374151",',
    '      formatter: function(v) {',
    '        if (!v) return "";',
    '        if (Math.abs(v) >= 1e6) return (v / 1e6).toFixed(1) + "M";',
    '        if (Math.abs(v) >= 1e3) return (v / 1e3).toFixed(1) + "K";',
    '        return String(v);',
    '      },',
    '      display: chartType === "bar",',
    '    };',
    '  }',
    '',
    '  function buildTooltipConfig() {',
    '    return {',
    '      enabled: true,',
    '      callbacks: {',
    '        label: function(ctx) {',
    '          var label = (ctx.dataset && ctx.dataset.label) ? ctx.dataset.label : "";',
    '          var value = ctx.parsed',
    '            ? (ctx.parsed.y !== undefined ? ctx.parsed.y : (ctx.parsed.x !== undefined ? ctx.parsed.x : 0))',
    '            : 0;',
    '          return (label ? label + ": " : "") + new Intl.NumberFormat("en").format(value || 0);',
    '        },',
    '      },',
    '    };',
    '  }',
    '',
    '  // Attach cross-chart click handler to a dashboard chart',
    '  function applyDashboardOnClick(chart, chartId, xField) {',
    '    chart.options.onClick = function(event, elements) {',
    '      if (!elements || !elements.length) {',
    '        // Click on empty area: deselect if this chart is the source',
    '        if (window.__dashSelection && window.__dashSelection.sourceChartId === chartId) {',
    '          window.__dashSelection = null;',
    '          if (typeof window.dashUpdateCrossFilter === "function") window.dashUpdateCrossFilter();',
    '        }',
    '        return;',
    '      }',
    '      var el = elements[0];',
    '      var label = String(chart.data.labels[el.index]);',
    '      var existing = window.__dashSelection;',
    '      var same = existing && existing.label === label && existing.sourceChartId === chartId;',
    '      window.__dashSelection = same ? null : {',
    '        label: label,',
    '        field: xField,',
    '        sourceChartId: chartId,',
    '        datasetIndex: el.datasetIndex,',
    '        dataIndex: el.index,',
    '      };',
    '      if (typeof window.dashUpdateCrossFilter === "function") window.dashUpdateCrossFilter();',
    '    };',
    '    chart.update("none");',
    '  }',
    '',
    '  function renderCharts() {',
    '    document.querySelectorAll("canvas[data-chart-config]").forEach(function(canvas) {',
    '      if (canvas.getAttribute("data-chart-rendered") === "true") return;',
    '      var encoded = canvas.getAttribute("data-chart-config");',
    '      if (!encoded) return;',
    '      try {',
    '        var config = JSON.parse(atob(encoded));',
    '        config.options = config.options || {};',
    '        config.options.responsive = true;',
    '        config.options.maintainAspectRatio = false;',
    '',
    '        if (isDashboard) {',
    '          config.options.animation = { duration: 300 };',
    '          config.options.plugins = config.options.plugins || {};',
    '          if (typeof ChartDataLabels !== "undefined") {',
    '            config.options.plugins.datalabels = buildDatalabelsConfig(config.type);',
    '          }',
    '          config.options.plugins.tooltip = buildTooltipConfig();',
    '        } else {',
    '          config.options.animation = { duration: 0 };',
    '        }',
    '',
    '        var chart = new Chart(canvas.getContext("2d"), config);',
    '        canvas.setAttribute("data-chart-rendered", "true");',
    '',
    '        if (isDashboard) {',
    '          var chartId = canvas.id;',
    '          var xField  = canvas.getAttribute("data-x-field") || "";',
    '          window.__dashCharts[chartId] = chart;',
    '          var rawEncoded = canvas.getAttribute("data-raw-data");',
    '          if (rawEncoded) {',
    '            try { window.__dashData[chartId] = JSON.parse(atob(rawEncoded)); } catch(e) {}',
    '          }',
    '          applyDashboardOnClick(chart, chartId, xField);',
    '        } else {',
    '          // Non-dashboard: convert canvas to static PNG image (existing behaviour)',
    '          requestAnimationFrame(function() {',
    '            replaceChartCanvasWithImage(canvas, chart, config);',
    '          });',
    '        }',
    '      } catch (e) {',
    '        console.error("Chart render error:", e);',
    '        var wrapper = canvas.closest("[data-chart-wrapper]") || canvas.parentNode;',
    '        wrapper.innerHTML = "<div style=\\"padding:16px;text-align:center;color:#dc2626;background:#fef2f2;border-radius:6px;font-size:13px;\\">" +',
    '          "<strong>Chart could not be rendered.</strong><br>Invalid chart configuration." +',
    '          "</div>";',
    '      }',
    '    });',
    '  }',
    '',
    '  if (document.readyState === "loading") {',
    '    document.addEventListener("DOMContentLoaded", renderCharts);',
    '  } else {',
    '    renderCharts();',
    '  }',
    '  window.renderCharts = renderCharts;',
    '})();',
    '',
    '// TOC active link tracking',
    '(function() {',
    '  var headings = document.querySelectorAll("h2[id], h3[id], h4[id]");',
    '  var tocLinks = document.querySelectorAll(".toc-link");',
    '  if (!headings.length || !tocLinks.length) return;',
    '  var observer = new IntersectionObserver(function(entries) {',
    '    entries.forEach(function(entry) {',
    '      if (entry.isIntersecting) {',
    '        tocLinks.forEach(function(link) { link.classList.remove("active"); });',
    '        var active = document.querySelector(".toc-link[href=\\"#" + entry.target.id + "\\"]");',
    '        if (active) active.classList.add("active");',
    '      }',
    '    });',
    '  }, { rootMargin: "-20% 0px -70% 0px" });',
    '  headings.forEach(function(h) { observer.observe(h); });',
    '})();',
    '',
    '// Search functionality',
    'function searchDocs(query) {',
    '  var highlights = document.querySelectorAll(".search-highlight");',
    '  highlights.forEach(function(el) {',
    '    var parent = el.parentNode;',
    '    parent.replaceChild(document.createTextNode(el.textContent), el);',
    '    parent.normalize();',
    '  });',
    '  if (!query || query.length < 2) return;',
    '  var walker = document.createTreeWalker(',
    '    document.querySelector(".main-content") || document.body,',
    '    NodeFilter.SHOW_TEXT, null',
    '  );',
    '  var textNodes = [];',
    '  var node;',
    '  while ((node = walker.nextNode())) {',
    '    if (node.nodeValue && node.nodeValue.toLowerCase().includes(query.toLowerCase())) {',
    '      textNodes.push(node);',
    '    }',
    '  }',
    '  textNodes.forEach(function(textNode) {',
    '    var escaped = query.replace(new RegExp("[.*+?^${}()|[\\]\\\\\\\\]", "g"), "\\\\$&");',
    '    var regex = new RegExp("(" + escaped + ")", "gi");',
    '    var span = document.createElement("span");',
    '    span.innerHTML = textNode.nodeValue.replace(regex, "<mark class=\\"search-highlight\\">$1</mark>");',
    '    textNode.parentNode.replaceChild(span, textNode);',
    '  });',
    '  var first = document.querySelector(".search-highlight");',
    '  if (first) first.scrollIntoView({ behavior: "smooth", block: "center" });',
    '}',
  ];

  return jsLines.join('\n');
}
