/**
 * Vector Index Generation Manager — DB compat module (Phase 1)
 *
 * Stores the logical → physical collection mapping used by the generation-based
 * reindex strategy (see plans/RAG_updates.md and plans/RAG_updates-review.md).
 *
 * Phase 1 establishes the backing table (`vector_index_generations`) and this
 * typed CRUD/status-transition module. Runtime resolution lands in Phase 2.
 *
 * The generation manager is PostgreSQL-only (consistent with the AGENTS.md rule
 * that all new DB access goes through the Kysely compat layer). All timestamps
 * are strings — see the pg type parser override in src/lib/db/kysely.ts.
 */

import { sql } from 'kysely';
import type { Generated, Kysely } from 'kysely';
import { getDb } from '../kysely';
import type { DB } from '../db-types';

// ============ Types ============

export type GenerationStatus =
  | 'building'
  | 'validating'
  | 'active'
  | 'retired'
  | 'failed';

export interface VectorIndexGeneration {
  id: number;
  logical_name: string;
  physical_name: string;
  generation: number;
  status: GenerationStatus;
  embedding_model: string | null;
  dimensions: number | null;
  chunking_version: number | null;
  created_at: string;
  activated_at: string | null;
  retire_after: string | null;
  notes: string | null;
}

export interface CreateGenerationInput {
  logicalName: string;
  physicalName: string;
  generation: number;
  status: GenerationStatus;
  embeddingModel?: string | null;
  dimensions?: number | null;
  chunkingVersion?: number | null;
  notes?: string | null;
}

// ============ Kysely table shape ============
//
// The global `DB` type in src/lib/db/db-types.ts is generated by
// `npm run db:types` against a live PostgreSQL instance, which is unavailable in
// this sandbox. We define the table shape locally and widen the Kysely instance
// type so the typed query builder works without hand-editing the generated file.
// Once `npm run db:types` has been run in a live environment, this module can
// reference the global `DB` type verbatim.

interface VectorIndexGenerationsTable {
  id: Generated<number>;
  logical_name: string;
  physical_name: string;
  generation: number;
  status: GenerationStatus;
  embedding_model: string | null;
  dimensions: number | null;
  chunking_version: number | null;
  created_at: Generated<string>;
  activated_at: string | null;
  retire_after: string | null;
  notes: string | null;
}

type VectorIndexDb = DB & {
  vector_index_generations: VectorIndexGenerationsTable;
};

async function getVectorIndexDb(): Promise<Kysely<VectorIndexDb>> {
  return (await getDb()) as unknown as Kysely<VectorIndexDb>;
}

// ============ Status state machine ============

const ALLOWED_TRANSITIONS: Readonly<Record<GenerationStatus, readonly GenerationStatus[]>> = {
  building: ['validating', 'failed'],
  validating: ['active', 'failed'],
  active: ['retired', 'failed'],
  retired: [],
  failed: [],
};

/**
 * Statuses that represent an in-progress candidate generation. Ingest mirrors
 * writes/deletes to these physical collections during a rebuild so the
 * candidate stays in sync (Phase 4).
 */
const CANDIDATE_STATUSES: GenerationStatus[] = ['building', 'validating'];

// ============ Reads ============

export async function getActiveGeneration(
  logicalName: string
): Promise<VectorIndexGeneration | undefined> {
  const db = await getVectorIndexDb();
  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .where('logical_name', '=', logicalName)
    .where('status', '=', 'active')
    .executeTakeFirst();
}

export async function getActiveMappings(): Promise<VectorIndexGeneration[]> {
  const db = await getVectorIndexDb();
  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .where('status', '=', 'active')
    .orderBy('logical_name')
    .execute();
}

/**
 * List every generation row regardless of status, ordered by logical name then
 * generation. Used by the Phase 6 script for next-generation computation, the
 * report subcommand, and rollback (to locate the previous active generation).
 */
export async function listGenerations(): Promise<VectorIndexGeneration[]> {
  const db = await getVectorIndexDb();
  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .orderBy('logical_name')
    .orderBy('generation')
    .execute();
}

/**
 * Get the in-progress candidate generation for a single logical name, if any.
 *
 * Candidates are generations in `building` or `validating` status — the
 * physical collection ingest mirrors writes/deletes to during a rebuild so the
 * candidate stays in sync (Phase 4).
 */
export async function getCandidateGeneration(
  logicalName: string
): Promise<VectorIndexGeneration | undefined> {
  const db = await getVectorIndexDb();
  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .where('logical_name', '=', logicalName)
    .where('status', 'in', CANDIDATE_STATUSES)
    .orderBy('generation')
    .executeTakeFirst();
}

/**
 * Get all in-progress candidate generations across every logical name.
 *
 * Used by ingest to discover candidate physical collections to mirror writes
 * and deletes to. Returns an empty array when no rebuild is in progress.
 */
export async function getCandidateGenerations(): Promise<VectorIndexGeneration[]> {
  const db = await getVectorIndexDb();
  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .where('status', 'in', CANDIDATE_STATUSES)
    .orderBy('logical_name')
    .orderBy('generation')
    .execute();
}

// ============ Create ============

export async function createGeneration(
  input: CreateGenerationInput
): Promise<VectorIndexGeneration> {
  const db = await getVectorIndexDb();
  return db
    .insertInto('vector_index_generations')
    .values({
      logical_name: input.logicalName,
      physical_name: input.physicalName,
      generation: input.generation,
      status: input.status,
      embedding_model: input.embeddingModel ?? null,
      dimensions: input.dimensions ?? null,
      chunking_version: input.chunkingVersion ?? null,
      notes: input.notes ?? null,
    })
    .returningAll()
    .executeTakeFirstOrThrow();
}

// ============ Status transitions ============

export async function transitionStatus(
  id: number,
  fromStatus: GenerationStatus[],
  toStatus: GenerationStatus
): Promise<VectorIndexGeneration | undefined> {
  if (fromStatus.length === 0) {
    throw new Error('transitionStatus requires at least one fromStatus');
  }

  for (const from of fromStatus) {
    if (!ALLOWED_TRANSITIONS[from].includes(toStatus)) {
      throw new Error(
        `Invalid vector-index generation status transition: ${from} → ${toStatus}`
      );
    }
  }

  const db = await getVectorIndexDb();

  if (toStatus === 'active') {
    await db
      .updateTable('vector_index_generations')
      .set({ status: 'active', activated_at: sql`NOW()` })
      .where('id', '=', id)
      .where('status', 'in', fromStatus)
      .execute();
  } else {
    await db
      .updateTable('vector_index_generations')
      .set({ status: toStatus })
      .where('id', '=', id)
      .where('status', 'in', fromStatus)
      .execute();
  }

  return db
    .selectFrom('vector_index_generations')
    .selectAll()
    .where('id', '=', id)
    .executeTakeFirst();
}

/**
 * Atomically activate the chosen generation for a logical name and retire any
 * other active generation for that same logical name. Runs in a single
 * transaction so the partial unique index on (logical_name WHERE status =
 * 'active') is never violated.
 */
export async function markActive(
  logicalName: string,
  generation: number
): Promise<VectorIndexGeneration | undefined> {
  const db = await getVectorIndexDb();

  return db.transaction().execute(async (trx) => {
    const target = await trx
      .selectFrom('vector_index_generations')
      .selectAll()
      .where('logical_name', '=', logicalName)
      .where('generation', '=', generation)
      .executeTakeFirst();

    if (!target) return undefined;

    // Retire any other active generation for this logical name.
    await trx
      .updateTable('vector_index_generations')
      .set({ status: 'retired' })
      .where('logical_name', '=', logicalName)
      .where('status', '=', 'active')
      .where('id', '!=', target.id)
      .execute();

    // Activate the chosen generation.
    await trx
      .updateTable('vector_index_generations')
      .set({ status: 'active', activated_at: sql`NOW()` })
      .where('id', '=', target.id)
      .execute();

    return trx
      .selectFrom('vector_index_generations')
      .selectAll()
      .where('id', '=', target.id)
      .executeTakeFirst();
  });
}
